<Project Sdk="Microsoft.NET.Sdk.Razor">

    <Import Project="../../common.props"/>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Secyud.Secits.Blazor.Generator\Secyud.Secits.Blazor.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>
    
    <ItemGroup>
        <None Update="**/*.razor.css" CssScope="s"/>
        <Content Remove="**/*.less"/>
        <None Include="**/*.less"/>
    </ItemGroup>

</Project>
