<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ProjectInfo>Test</ProjectInfo>
    </PropertyGroup>

    <Import Project="../../common.props"/>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="xunit"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Secyud.Secits.Blazor\Secyud.Secits.Blazor.csproj" />
    </ItemGroup>

</Project>