<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <ProjectInfo>App</ProjectInfo>
    </PropertyGroup>

    <Import Project="../../common.props"/>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer"  PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Secyud.Secits.Blazor.Demo\Secyud.Secits.Blazor.Demo.csproj"/>
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\css\app.css" />
    </ItemGroup>

</Project>
