<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <IsApp>true</IsApp>
    </PropertyGroup>

    <Import Project="../../common.props"/>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.0"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.0" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Secyud.Secits.Blazor.Demo\Secyud.Secits.Blazor.Demo.csproj"/>
    </ItemGroup>

</Project>
