using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Secyud.Secits.Blazor;

/// <summary>
/// A sample source generator that creates a custom report based on class properties. The target class should be annotated with the 'Generators.ReportAttribute' attribute.
/// When using the source code as a baseline, an incremental source generator is preferable because it reduces the performance overhead.
/// </summary>
[Generator]
public class SValueGeneratorWithAttributes : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Filter classes annotated with the [Report] attribute. Only filtered Syntax Nodes can trigger code generation.
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                (s, _) => s is StructDeclarationSyntax,
                (ctx, _) => GetStructDeclarationForSourceGen(ctx))
            .Where(t => t.attributeFound)
            .Select((t, _) => t.Item1);

        // Generate the source code.
        context.RegisterSourceOutput(context.CompilationProvider.Combine(provider.Collect()),
            ((ctx, t) => GenerateCode(ctx, t.Left, t.Right)));
    }

    /// <summary>
    /// Checks whether the Node is annotated with the [Report] attribute and maps syntax context to the specific node type (ClassDeclarationSyntax).
    /// </summary>
    /// <param name="context">Syntax context, based on CreateSyntaxProvider predicate</param>
    /// <returns>The specific cast and whether the attribute was found.</returns>
    private static (StructDeclarationSyntax, bool attributeFound) GetStructDeclarationForSourceGen(
        GeneratorSyntaxContext context)
    {
        var syntax = (StructDeclarationSyntax)context.Node;

        // Go through all attributes of the class.
        foreach (AttributeListSyntax attributeListSyntax in syntax.AttributeLists)
        foreach (AttributeSyntax attributeSyntax in attributeListSyntax.Attributes)
        {
            if (context.SemanticModel.GetSymbolInfo(attributeSyntax).Symbol is not IMethodSymbol attributeSymbol)
                continue;

            string attributeName = attributeSymbol.ContainingType.ToDisplayString();

            // Check the full name of the [Report] attribute.
            if (attributeName == $"{Namespace}.{AttributeName}")
                return (syntax, true);
        }

        return (syntax, false);
    }

    private const string Namespace = "Secyud.Secits.Blazor";
    private const string AttributeName = "SValueAttribute";

    /// <summary>
    /// Generate code action.
    /// It will be executed on specific nodes (ClassDeclarationSyntax annotated with the [Report] attribute) changed by the user.
    /// </summary>
    /// <param name="context">Source generation context used to add source files.</param>
    /// <param name="compilation">Compilation used to provide access to the Semantic Model.</param>
    /// <param name="structDeclarations">Nodes annotated with the [Report] attribute that trigger the generate action.</param>
    private void GenerateCode(SourceProductionContext context, Compilation compilation,
        ImmutableArray<StructDeclarationSyntax> structDeclarations)
    {
        // Go through all filtered class declarations.
        foreach (var classDeclarationSyntax in structDeclarations)
        {
            // We need to get semantic model of the class to retrieve metadata.
            var semanticModel = compilation.GetSemanticModel(classDeclarationSyntax.SyntaxTree);

            // Symbols allow us to get the compile-time information.
            if (semanticModel.GetDeclaredSymbol(classDeclarationSyntax) is not INamedTypeSymbol classSymbol)
                continue;

            var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();

            // 'Identifier' means the token of the node. Get class name from the syntax node.
            var structName = classDeclarationSyntax.Identifier.Text;

            // Build up the source code
            var code = $$"""
                         // <auto-generated/>

                         using System;
                         using System.Collections.Generic;

                         #nullable enable
                         namespace {{namespaceName}};

                         public readonly partial struct {{structName}}(SValue value): IEquatable<{{structName}}>
                         {
                             private SValue Value { get; } = value;
                             
                             public static implicit operator SValue({{structName}} value)
                             {
                                 return value.Value;
                             }
                             
                             public static implicit operator {{structName}}({{structName}}[] values)
                             {
                                 return string.Join(' ', values
                                     .Where(u => u.Value is { IsClass: true, IsNull: false })
                                     .Select(u => u.Value.Value)
                                 );
                             }
                             
                             public static implicit operator {{structName}}(string str)
                             {
                                 return new SValue(str);
                             }
                             
                             public static implicit operator {{structName}}(SValue value)
                             {
                                 return new {{structName}}(value);
                             }
                             
                             public override bool Equals(object? obj)
                             {
                                 return obj is {{structName}} other && Equals(other);
                             }
                             
                             public override int GetHashCode()
                             {
                                 return Value.GetHashCode();
                             }
                             
                             public static bool operator ==({{structName}} left, {{structName}} right)
                             {
                                 return left.Equals(right);
                             }
                             
                             public static bool operator !=({{structName}} left, {{structName}} right)
                             {
                                 return !(left == right);
                             }
                             
                             public bool Equals({{structName}} other)
                             {
                                 return Value.Equals(other.Value);
                             }
                         }
                         """;

            // Add the source code to the compilation.
            context.AddSource($"{structName}.g.cs", SourceText.From(code, Encoding.UTF8));
        }
    }
}