<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <ProjectInfo>App</ProjectInfo>
    </PropertyGroup>

    <Import Project="../../common.props"/>

    <ItemGroup Condition="'$(ReferenceType)' == 'Package'">
        <PackageReference Include="Secyud.DemoUtils"/>
    </ItemGroup>

    <ItemGroup Condition="'$(ReferenceType)' == 'Project'">
        <ProjectReference Include="$(UtilsSrc)/Secyud.DemoUtils/Secyud.DemoUtils.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Secyud.Secits.Blazor\Secyud.Secits.Blazor.csproj"/>
    </ItemGroup>

</Project>
